### ISSUE TITLE
error running the tutorials

### ISSUE THREAD

**Issue by Igallardo22** [viebboy/PyGOP#2]
Hi,

I`m trying to run the tutorials (both of them) but I get the same error in the executions. 
_RuntimeError: Search process using CPU terminated but no result exists!_
![miniceleb](https://user-images.githubusercontent.com/740938/99963065-7ddbd980-2d91-11eb-89b5-efed69222cfe.JPG)
![minst](https://user-images.githubusercontent.com/740938/99963067-7e747000-2d91-11eb-98fe-7d82d9d3ac5f.JPG)

I have installed all the recommended dependencies and versions. I don`t where the error can be.

Thanks in advance!

**Comment by viebboy** [comment]
Hi, it seems that you were running the library on Windows. Unfortunately, at the moment, our package can only be run on linux OS.
